"""Phase 15 -- ML meta-labeling and regime research.

The ML model is a SECONDARY FILTER around a deterministic primary strategy::

    primary StrategySpec -> candidate signal (a primary trade EPISODE)
        -> causal features / regime  ->  ML meta-labeler  ->  TAKE / SKIP
        -> closed TargetSchedule  ->  C++ Quant Core  ->  Fill-derived economics
        -> Reliability Validation  ->  Experiment Registry

It replaces nothing. Official PnL stays C++ Fill-derived, risk stays
deterministic, verdicts stay with the reliability policy, and truth about what
has already been run stays with the experiment registry.

Phase 15A is DESIGN + FREEZE ONLY: schemas, deterministic builders, guards and
tests. No real model is trained, no ML performance is inspected, and 2025 is
never touched.
"""
from __future__ import annotations

from alpha_agent.ml.adjudication import (
    ML_DIAGNOSTIC_METRICS,
    PHASE_13_5C_RELIABILITY_POLICY_FINGERPRINT,
    PHASE_15_BH_FAMILY_SIZE,
    PHASE_15_PLACEBO_EMPIRICAL_P_MAX,
    PHASE_15_REASON_META_NOT_BEAT_PRIMARY,
    PHASE_15_REASON_ML_VALUE_ADD_CONFIRMED,
    PHASE_15_REASON_PLACEBO_NOT_SIGNIFICANT,
    PHASE_15_REASON_TYPED_REFUSAL,
    REPORTED_ECONOMIC_METRICS,
    MLBaselineComparisonPlan,
    MLMultipleTestingPlan,
    MLPlaceboPlan,
    MLValidationSpec,
    Phase15TrialAdjudication,
    adjudicate_phase_15_trial,
    assert_null_plan_fits_frozen_compute_budget,
    assert_phase_15_adjudication_rules_frozen,
    assert_protocol_and_policy_agree,
    assert_reliability_policy_gates_are_predeclared,
    assert_reliability_policy_inherited_unchanged,
    build_phase_15_validation_spec,
    multiple_testing_plan_from_manifest,
    phase_15_bh_family_p_values,
    phase_15_cost_stress_plan,
    phase_15_null_test_config,
    phase_15_reliability_policy,
    placebo_empirical_p,
)
from alpha_agent.ml.allowlist import (
    KNOWN_AUDIT_ONLY_FIELDS,
    assert_model_inputs_allowed,
    model_input_allowlist,
)
from alpha_agent.ml.enums import (
    DevelopmentSplitRole,
    EpisodeExclusionReason,
    FoldKind,
    LabelKind,
    MetaLabelAction,
    MLModelFamily,
    MLRefusalReason,
    MLTrialRole,
    ModelSelectionObjective,
    ModelSelectionTieBreak,
    PreprocessingKind,
    RegimeSpecKind,
)
from alpha_agent.ml.episodes import (
    EconomicReconciliation,
    EpisodeAttribution,
    EpisodeEconomics,
    PrimaryEpisode,
    attribute_episode_economics,
    attribute_trades_to_episodes,
    extract_primary_episodes,
    reconcile_episode_economics,
)
from alpha_agent.ml.errors import (
    FoldIsolationError,
    ForbiddenDependency,
    ForbiddenModelInput,
    InsufficientEventsError,
    LeakageError,
    ManifestFrozenError,
    MLDependencyMissing,
    MLProtocolError,
    NetworkAccessForbidden,
    RandomSplitForbidden,
)
from alpha_agent.ml.execution import (
    MetaLabeledScheduleDiff,
    assert_aligned_evaluation_support,
    assert_closed_action_space,
    build_meta_labeled_schedule,
)
from alpha_agent.ml.features import (
    MLFeature,
    MLFeatureSetSpec,
    assert_feature_set_signal_safe,
)
from alpha_agent.ml.identity import (
    PHASE_15_MT_FAMILY,
    MLExperimentSpec,
    ml_composite_fingerprint,
    ml_parameter_variant_identity,
    ml_trial_discriminator,
    query_registry_before_running,
)
from alpha_agent.ml.labels import (
    MetaLabelEvent,
    MetaLabelEventSet,
    MetaLabelSpec,
    assert_event_causality,
    build_meta_label_events,
)
from alpha_agent.ml.models import (
    DEFAULT_ML_RANDOM_SEED,
    FORBIDDEN_ML_PACKAGES,
    FROZEN_HYPERPARAMETER_GRID,
    FROZEN_TAKE_THRESHOLD,
    MLModelSpec,
    ModelSearchSpec,
    assert_frozen_take_threshold,
    assert_no_forbidden_ml_packages,
    assert_selection_is_within_search,
    frozen_model_search,
    ml_dependency_status,
    ml_environment_provenance,
)
from alpha_agent.ml.planes import (
    assert_planes_are_real,
    assert_sixty_complete_identities,
    ml_dataset_plane_fingerprint,
    phase_13_5c_dataset_fingerprints,
    phase_15_identity_planes,
    phase_15_pre_run_identity_rows,
    phase_15_registry_preflight,
    planes_payload,
)
from alpha_agent.ml.predictions import (
    MLPrediction,
    MLPredictionFrame,
    assert_oof_provenance,
)
from alpha_agent.ml.preprocessing import FoldFittedTransform, PreprocessingSpec
from alpha_agent.ml.regime import RegimeSpec
from alpha_agent.ml.splits import (
    EventTimeline,
    Fold,
    NestedCVSpec,
    assert_fold_is_causal,
    assert_global_temporal_isolation,
    build_inner_folds,
    build_outer_folds,
    pooled_isolation_report,
    refuse_random_split,
)
from alpha_agent.ml.training import MLTrainingReport, MLTrainingSpec, run_nested_cv
from alpha_agent.ml.trials import (
    MLIdentityPlanes,
    assert_one_identity_per_trial,
    experiment_spec_for_trial,
    trial_discriminator,
    trial_identity_rows,
)

__all__ = [
    "DEFAULT_ML_RANDOM_SEED",
    "FORBIDDEN_ML_PACKAGES",
    "FROZEN_HYPERPARAMETER_GRID",
    "FROZEN_TAKE_THRESHOLD",
    "KNOWN_AUDIT_ONLY_FIELDS",
    "ML_DIAGNOSTIC_METRICS",
    "PHASE_13_5C_RELIABILITY_POLICY_FINGERPRINT",
    "PHASE_15_BH_FAMILY_SIZE",
    "PHASE_15_MT_FAMILY",
    "PHASE_15_PLACEBO_EMPIRICAL_P_MAX",
    "PHASE_15_REASON_META_NOT_BEAT_PRIMARY",
    "PHASE_15_REASON_ML_VALUE_ADD_CONFIRMED",
    "PHASE_15_REASON_PLACEBO_NOT_SIGNIFICANT",
    "PHASE_15_REASON_TYPED_REFUSAL",
    "REPORTED_ECONOMIC_METRICS",
    "DevelopmentSplitRole",
    "EconomicReconciliation",
    "EpisodeAttribution",
    "EpisodeEconomics",
    "EpisodeExclusionReason",
    "EventTimeline",
    "Fold",
    "FoldFittedTransform",
    "FoldIsolationError",
    "FoldKind",
    "ForbiddenDependency",
    "ForbiddenModelInput",
    "InsufficientEventsError",
    "LabelKind",
    "LeakageError",
    "MLBaselineComparisonPlan",
    "MLDependencyMissing",
    "MLExperimentSpec",
    "MLFeature",
    "MLFeatureSetSpec",
    "MLIdentityPlanes",
    "MLModelFamily",
    "MLModelSpec",
    "MLMultipleTestingPlan",
    "MLPlaceboPlan",
    "MLPrediction",
    "MLPredictionFrame",
    "MLProtocolError",
    "MLRefusalReason",
    "MLTrainingReport",
    "MLTrainingSpec",
    "MLTrialRole",
    "MLValidationSpec",
    "ManifestFrozenError",
    "MetaLabelAction",
    "MetaLabelEvent",
    "MetaLabelEventSet",
    "MetaLabelSpec",
    "MetaLabeledScheduleDiff",
    "ModelSearchSpec",
    "ModelSelectionObjective",
    "ModelSelectionTieBreak",
    "NestedCVSpec",
    "NetworkAccessForbidden",
    "Phase15TrialAdjudication",
    "PreprocessingKind",
    "PreprocessingSpec",
    "PrimaryEpisode",
    "RandomSplitForbidden",
    "RegimeSpec",
    "RegimeSpecKind",
    "adjudicate_phase_15_trial",
    "assert_aligned_evaluation_support",
    "assert_closed_action_space",
    "assert_event_causality",
    "assert_feature_set_signal_safe",
    "assert_fold_is_causal",
    "assert_frozen_take_threshold",
    "assert_global_temporal_isolation",
    "assert_model_inputs_allowed",
    "assert_no_forbidden_ml_packages",
    "assert_null_plan_fits_frozen_compute_budget",
    "assert_one_identity_per_trial",
    "assert_oof_provenance",
    "assert_phase_15_adjudication_rules_frozen",
    "assert_planes_are_real",
    "assert_protocol_and_policy_agree",
    "assert_reliability_policy_gates_are_predeclared",
    "assert_reliability_policy_inherited_unchanged",
    "assert_selection_is_within_search",
    "assert_sixty_complete_identities",
    "attribute_episode_economics",
    "attribute_trades_to_episodes",
    "build_inner_folds",
    "build_meta_label_events",
    "build_meta_labeled_schedule",
    "build_outer_folds",
    "build_phase_15_validation_spec",
    "experiment_spec_for_trial",
    "extract_primary_episodes",
    "frozen_model_search",
    "ml_composite_fingerprint",
    "ml_dataset_plane_fingerprint",
    "ml_dependency_status",
    "ml_environment_provenance",
    "ml_parameter_variant_identity",
    "ml_trial_discriminator",
    "model_input_allowlist",
    "multiple_testing_plan_from_manifest",
    "phase_13_5c_dataset_fingerprints",
    "phase_15_bh_family_p_values",
    "phase_15_cost_stress_plan",
    "phase_15_identity_planes",
    "phase_15_null_test_config",
    "phase_15_pre_run_identity_rows",
    "phase_15_registry_preflight",
    "phase_15_reliability_policy",
    "placebo_empirical_p",
    "planes_payload",
    "pooled_isolation_report",
    "query_registry_before_running",
    "reconcile_episode_economics",
    "refuse_random_split",
    "run_nested_cv",
    "trial_discriminator",
    "trial_identity_rows",
]
