"""Explicit data-provenance tagging for the Phase 22 crypto/on-chain extension.

Prompt 22 asks for a separate alternative-data module for BTC/ETH derivatives
and on-chain features. The Phase 22 review-gate decision (2026-09-11) approved
a **synthetic-scaffold-only** implementation: zero network calls, zero paid API
use, zero new vendor connections, no vendor lock-in, no 2025 holdout access.
Every dataset, feature frame, backtest result, validation report, chart, and
registry row this package produces must carry an explicit provenance tag, and
none of it may be presented as real market evidence, become paper-trading
eligible, or join the real Phase 13.5C+ statistical family.

This module is the single choke point that makes that structural rather than a
comment: :class:`CryptoDataProvenance` is a required field on every payload the
package returns downstream, ``role`` is a closed two-value enum, and
``assert_synthetic()`` is the one guard every constructor in this package calls
before returning data.
"""
from __future__ import annotations

from datetime import UTC, datetime
from enum import Enum

from pydantic import BaseModel, Field


class DataProvenanceRole(str, Enum):
    """Closed set. ``REAL`` is reserved for a byte-verified vendor delivery --
    Phase 22 connects none (no CME BTC/ETH futures acquisition, no perp/on-chain
    vendor). ``SYNTHETIC`` is every row this package can currently produce."""

    REAL = "REAL"
    SYNTHETIC = "SYNTHETIC"


#: Vendor name for the deterministic synthetic-fixture generator. Deliberately
#: not shaped like a real vendor name, so a downstream reader (registry row,
#: chart, report) can never mistake it for licensed market data.
SYNTHETIC_FIXTURE_VENDOR = "SYNTHETIC_FIXTURE_V1"

#: Rendered verbatim by every Phase 22 UI surface and stored verbatim on every
#: Phase 22 synthetic registry row (see :mod:`alpha_agent.crypto.synthetic_registry`).
SYNTHETIC_BANNER = (
    "SYNTHETIC DATA -- NOT REAL MARKET EVIDENCE. Generated by a deterministic "
    "seeded fixture generator for engineering / scientific-pipeline testing "
    "only. Never an authoritative scientific verdict, never paper-trading "
    "eligible, never part of the real experiment registry or its BH/FDR family."
)


class RealVendorNotConnectedError(RuntimeError):
    """Raised by any code path that would need a REAL crypto vendor connection.

    Phase 22 ships zero real vendor integrations (prompts/22 review-gate
    decision): no network call, no API key, no paid vendor. This is the single
    choke point every adapter and fixture builder in this package raises
    through rather than silently returning synthetic data under a REAL label.
    """


class CryptoDataProvenance(BaseModel):
    """Attached to every row/frame/result the crypto package produces."""

    model_config = {"frozen": True, "extra": "forbid"}

    schema_version: str = "crypto-provenance/1"
    role: DataProvenanceRole
    vendor: str
    series_kind: str
    fixture_seed: int | None = None
    generated_at_utc: str = Field(default_factory=lambda: datetime.now(UTC).isoformat())
    notes: str = ""

    def assert_synthetic(self) -> CryptoDataProvenance:
        """Hard-fail unless ``role == SYNTHETIC``. Every synthetic-fixture
        constructor calls this before returning; every consumer (dataset
        assembly, registry write, UI render) may call it again defensively."""
        if self.role is not DataProvenanceRole.SYNTHETIC:
            raise RealVendorNotConnectedError(
                f"Phase 22 scaffold only supports role=SYNTHETIC data; got "
                f"role={self.role.value} from vendor={self.vendor!r} "
                f"(series_kind={self.series_kind!r}). No real crypto vendor is "
                "connected -- see docs/CRYPTO_ONCHAIN_EXTENSION.md."
            )
        return self

    def content_identity(self) -> str:
        """Stable scientific/content identity for this provenance record --
        deliberately EXCLUDES ``generated_at_utc``. Phase 22.1: rerunning
        byte-identical synthetic inputs on a different day must not change any
        downstream content identity solely because the wall clock moved.
        ``generated_at_utc`` remains ordinary bookkeeping metadata (when this
        record was built), never a scientific input."""
        from alpha_agent.validation.fingerprint import fingerprint

        return fingerprint(
            "cryptoprovenance1",
            {
                "schema": self.schema_version,
                "role": self.role.value,
                "vendor": self.vendor,
                "series_kind": self.series_kind,
                "fixture_seed": self.fixture_seed,
                "notes": self.notes,
            },
        )


def synthetic_provenance(series_kind: str, *, seed: int, notes: str = "") -> CryptoDataProvenance:
    """The one constructor every Phase 22 synthetic-fixture function uses."""
    return CryptoDataProvenance(
        role=DataProvenanceRole.SYNTHETIC,
        vendor=SYNTHETIC_FIXTURE_VENDOR,
        series_kind=series_kind,
        fixture_seed=seed,
        notes=notes,
    ).assert_synthetic()
